export const quotes = [
{
  category: "time",
  items: [
    { quote: "Time is an illusion.", author: "Albert Einstein" },
    { quote: "Lost time is never found again.", author: "Benjamin Franklin" },
    { quote: "The future depends on what we do in the present.", author: "Mahatma Gandhi" },
    { quote: "Time flies over us, but leaves its shadow behind.", author: "Nathaniel Hawthorne" },
    { quote: "Time you enjoy wasting is not wasted time.", author: "Bertrand Russell" },
    { quote: "The key is in not spending time, but in investing it.", author: "Stephen R. Covey" },
    { quote: "Time is the wisest counselor of all.", author: "Pericles" },
    { quote: "We must use time as a tool, not as a couch.", author: "John F. Kennedy" },
    { quote: "They always say time changes things, but you actually have to change them yourself.", author: "Andy Warhol" },
    { quote: "Better three hours too soon than a minute too late.", author: "William Shakespeare" },
    { quote: "Time takes it all, whether you want it to or not.", author: "Stephen King" },
    { quote: "You may delay, but time will not.", author: "Benjamin Franklin" },
    { quote: "Time is what we want most, but what we use worst.", author: "William Penn" },
    { quote: "Clocks slay time... time is dead as long as it is being clicked off by little wheels.", author: "William Faulkner" },
    { quote: "Time is a created thing. To say 'I don’t have time' is to say 'I don’t want to.'", author: "Lao Tzu" },
    { quote: "Time moves in one direction, memory in another.", author: "William Gibson" },
    { quote: "All we have to decide is what to do with the time that is given us.", author: "J.R.R. Tolkien" },
    { quote: "The trouble is, you think you have time.", author: "Buddha" },
    { quote: "Time waits for no one.", author: "Anonymous" },
    { quote: "You can’t make up for lost time. You can only do better in the future.", author: "Ashley Ormon" },
    { quote: "Time brings all things to pass.", author: "Aeschylus" },
    { quote: "Time changes everything except something within us which is always surprised by change.", author: "Thomas Hardy" },
    { quote: "Time is a storm in which we are all lost.", author: "William Carlos Williams" },
    { quote: "Time is the most valuable thing a man can spend.", author: "Theophrastus" },
    { quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { quote: "Time heals what reason cannot.", author: "Seneca" },
    { quote: "There’s only one thing more precious than our time and that’s who we spend it on.", author: "Leo Christopher" }
  ]
},
{
  category: "space",
  items: [
    { quote: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
    { quote: "To confine our attention to terrestrial matters would be to limit the human spirit.", author: "Stephen Hawking" },
    { quote: "The Earth is the cradle of humanity, but one cannot live in a cradle forever.", author: "Konstantin Tsiolkovsky" },
    { quote: "The cosmos is within us. We are made of star-stuff.", author: "Carl Sagan" },
    { quote: "Space exploration is a force of nature unto itself.", author: "Neil deGrasse Tyson" },
    { quote: "For small creatures such as we, the vastness is bearable only through love.", author: "Carl Sagan" },
    { quote: "Across the sea of space, the stars are other suns.", author: "Carl Sagan" },
    { quote: "Man must rise above the Earth—to the top of the atmosphere and beyond—for only thus will he fully understand the world in which he lives.", author: "Socrates" },
    { quote: "The universe doesn’t allow perfection.", author: "Stephen Hawking" },
    { quote: "We are just an advanced breed of monkeys on a minor planet of a very average star.", author: "Stephen Hawking" },
    { quote: "The universe is under no obligation to make sense to you.", author: "Neil deGrasse Tyson" },
    { quote: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
    { quote: "When I first looked back at the Earth, standing on the Moon, I cried.", author: "Alan Shepard" },
    { quote: "To the mind that is still, the whole universe surrenders.", author: "Lao Tzu" },
    { quote: "Exploration knows no bounds.", author: "Anonymous" },
    { quote: "We are the cosmos made conscious and life is the means by which the universe understands itself.", author: "Brian Cox" },
    { quote: "Looking at these stars suddenly dwarfed my own troubles and all the gravities of terrestrial life.", author: "H.G. Wells" },
    { quote: "That’s one small step for man, one giant leap for mankind.", author: "Neil Armstrong" },
    { quote: "Astronomy compels the soul to look upward, and leads us from this world to another.", author: "Plato" },
    { quote: "The universe is not only stranger than we imagine, it is stranger than we can imagine.", author: "Arthur Eddington" },
    { quote: "We are finite, yet we are capable of the infinite.", author: "Carl Sagan" },
    { quote: "Every one of us is, in the cosmic perspective, precious.", author: "Carl Sagan" },
    { quote: "Space is to place as eternity is to time.", author: "Joseph Joubert" },
    { quote: "The universe is change; our life is what our thoughts make it.", author: "Marcus Aurelius" },
    { quote: "In space, no one can hear you scream.", author: "Anonymous" },
    { quote: "There are no passengers on spaceship Earth. We are all crew.", author: "Marshall McLuhan" },
    { quote: "The stars don’t look bigger, but they do look brighter.", author: "Sally Ride" }
  ]
},
{
  category: "science",
  items: [
    { quote: "Science is a way of thinking much more than it is a body of knowledge.", author: "Carl Sagan" },
    { quote: "The important thing is not to stop questioning.", author: "Albert Einstein" },
    { quote: "Equipped with his five senses, man explores the universe around him and calls the adventure Science.", author: "Edwin Hubble" },
    { quote: "The good thing about science is that it's true whether or not you believe in it.", author: "Neil deGrasse Tyson" },
    { quote: "Science knows no country, because knowledge belongs to humanity.", author: "Louis Pasteur" },
    { quote: "The whole of science is nothing more than a refinement of everyday thinking.", author: "Albert Einstein" },
    { quote: "Science is organized knowledge. Wisdom is organized life.", author: "Immanuel Kant" },
    { quote: "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", author: "Stephen Hawking" },
    { quote: "The art and science of asking questions is the source of all knowledge.", author: "Thomas Berger" },
    { quote: "Science without religion is lame, religion without science is blind.", author: "Albert Einstein" },
    { quote: "There is no law except the law that there is no law.", author: "John Archibald Wheeler" },
    { quote: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
    { quote: "In questions of science, the authority of a thousand is not worth the humble reasoning of a single individual.", author: "Galileo Galilei" },
    { quote: "Science and everyday life cannot and should not be separated.", author: "Rosalind Franklin" },
    { quote: "All truths are easy to understand once they are discovered; the point is to discover them.", author: "Galileo Galilei" },
    { quote: "An experiment is a question which science poses to Nature.", author: "Max Planck" },
    { quote: "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.", author: "Isaac Asimov" },
    { quote: "Research is what I’m doing when I don’t know what I’m doing.", author: "Wernher von Braun" },
    { quote: "Science is magic that works.", author: "Kurt Vonnegut" },
    { quote: "The universe is made of stories, not atoms.", author: "Muriel Rukeyser" },
    { quote: "Every brilliant experiment, like every great work of art, starts with an act of imagination.", author: "Jonah Lehrer" },
    { quote: "The scientist is not a person who gives the right answers, he’s one who asks the right questions.", author: "Claude Lévi-Strauss" },
    { quote: "Science never solves a problem without creating ten more.", author: "George Bernard Shaw" },
    { quote: "Science is simply common sense at its best.", author: "Thomas Huxley" },
    { quote: "We live in a society exquisitely dependent on science and technology, in which hardly anyone knows anything about science and technology.", author: "Carl Sagan" },
    { quote: "Nature is pleased with simplicity.", author: "Isaac Newton" },
    { quote: "The scientist is motivated primarily by curiosity and a desire for truth.", author: "Irving Langmuir" }
  ]
},
{
  category: "reality",
  items: [
    { quote: "Reality is that which, when you stop believing in it, doesn’t go away.", author: "Philip K. Dick" },
    { quote: "We don't see things as they are, we see them as we are.", author: "Anaïs Nin" },
    { quote: "The only real thing is now.", author: "Eckhart Tolle" },
    { quote: "What we observe is not nature itself, but nature exposed to our method of questioning.", author: "Werner Heisenberg" },
    { quote: "Reality leaves a lot to the imagination.", author: "John Lennon" },
    { quote: "Perception is reality.", author: "Lee Atwater" },
    { quote: "The truth will set you free, but first it will make you miserable.", author: "James A. Garfield" },
    { quote: "Reality is merely an illusion, albeit a very persistent one.", author: "Albert Einstein" },
    { quote: "We shape our tools and thereafter our tools shape us.", author: "Marshall McLuhan" },
    { quote: "There are no facts, only interpretations.", author: "Friedrich Nietzsche" },
    { quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
    { quote: "The greatest obstacle to discovery is not ignorance—it is the illusion of knowledge.", author: "Daniel J. Boorstin" },
    { quote: "The world is full of magic things patiently waiting for our senses to grow sharper.", author: "W.B. Yeats" },
    { quote: "Illusion is the first of all pleasures.", author: "Oscar Wilde" },
    { quote: "There is no reality except the one contained within us.", author: "Hermann Hesse" },
    { quote: "Sometimes people don’t want to hear the truth because they don’t want their illusions destroyed.", author: "Friedrich Nietzsche" },
    { quote: "You create your own reality.", author: "Jane Roberts" },
    { quote: "Life is not a problem to be solved, but a reality to be experienced.", author: "Søren Kierkegaard" },
    { quote: "The map is not the territory.", author: "Alfred Korzybski" },
    { quote: "What we call reality is an agreement the mind makes.", author: "Deepak Chopra" },
    { quote: "Nothing is real until it is experienced.", author: "John Keats" },
    { quote: "Reality exists in the human mind, and nowhere else.", author: "George Orwell" },
    { quote: "You don’t see the world as it is; you see it as you are.", author: "Anonymous" },
    { quote: "Reality always wins.", author: "Elizabeth Hardwick" },
    { quote: "Everything we call real is made of things that cannot be regarded as real.", author: "Niels Bohr" },
    { quote: "The truth may hurt for a while, but lies hurt forever.", author: "Anonymous" },
    { quote: "The more real you get, the more unreal the world becomes.", author: "John Lennon" },
    { quote: "The eye sees only what the mind is prepared to comprehend.", author: "Henri Bergson" }
  ]
}];